# Do not edit. Generated by the configure script.
{
  "variables": {
    "host_arch": "x64", 
    "LuaIO_prefix": "", 
    "uv_library": "static_library", 
    "LuaIO_debug": "true", 
    "target_arch": "x64"
  }, 
  "target_defaults": {
    "libraries": [], 
    "defines": [], 
    "cflags": [], 
    "include_dirs": []
  }
}
