# Do not edit. Generated by the configure script.
{
  "variables": {
    "luaio_prefix": "", 
    "luaio_debug": "false", 
    "openssl_no_asm": 0, 
    "target_arch": "x64", 
    "openssl_fips": "", 
    "uv_library": "static_library", 
    "host_arch": "x64", 
    "node_byteorder": "little"
  }, 
  "target_defaults": {
    "libraries": [], 
    "defines": [], 
    "cflags": [], 
    "include_dirs": []
  }
}
